export const DEFAULT_FIGURES = [
	{
		id: 1,
		name: "El gallo",
		src: "figures/mexican/1.webp",
		imageURL: "",
	},
	{
		id: 2,
		name: "El diablito",
		src: "figures/mexican/2.webp",
		imageURL: "",
	},
	{
		id: 3,
		name: "La dama",
		src: "figures/mexican/3.webp",
		imageURL: "",
	},
	{
		id: 4,
		name: "El catrin",
		src: "figures/mexican/4.webp",
		imageURL: "",
	},
	{
		id: 5,
		name: "El paraguas",
		src: "figures/mexican/5.webp",
		imageURL: "",
	},
	{
		id: 6,
		name: "La sirena",
		src: "figures/mexican/6.webp",
		imageURL: "",
	},
	{
		id: 7,
		name: "La escalera",
		src: "figures/mexican/7.webp",
		imageURL: "",
	},
	{
		id: 8,
		name: "La botella",
		src: "figures/mexican/8.webp",
		imageURL: "",
	},
	{
		id: 9,
		name: "El barril",
		src: "figures/mexican/9.webp",
		imageURL: "",
	},
	{
		id: 10,
		name: "El arbol",
		src: "figures/mexican/10.webp",
		imageURL: "",
	},
	{
		id: 11,
		name: "El melon",
		src: "figures/mexican/11.webp",
		imageURL: "",
	},
	{
		id: 12,
		name: "El valiente",
		src: "figures/mexican/12.webp",
		imageURL: "",
	},
	{
		id: 13,
		name: "El gorrito",
		src: "figures/mexican/13.webp",
		imageURL: "",
	},
	{
		id: 14,
		name: "La muerte",
		src: "figures/mexican/14.webp",
		imageURL: "",
	},
	{
		id: 15,
		name: "La pera",
		src: "figures/mexican/15.webp",
		imageURL: "",
	},
	{
		id: 16,
		name: "La bandera",
		src: "figures/mexican/16.webp",
		imageURL: "",
	},
	{
		id: 17,
		name: "El bandolon",
		src: "figures/mexican/17.webp",
		imageURL: "",
	},
	{
		id: 18,
		name: "El violoncello",
		src: "figures/mexican/18.webp",
		imageURL: "",
	},
	{
		id: 19,
		name: "La garza",
		src: "figures/mexican/19.webp",
		imageURL: "",
	},
	{
		id: 20,
		name: "El pajaro",
		src: "figures/mexican/20.webp",
		imageURL: "",
	},
	{
		id: 21,
		name: "La mano",
		src: "figures/mexican/21.webp",
		imageURL: "",
	},
	{
		id: 22,
		name: "La bota",
		src: "figures/mexican/22.webp",
		imageURL: "",
	},
	{
		id: 23,
		name: "La luna",
		src: "figures/mexican/23.webp",
		imageURL: "",
	},
	{
		id: 24,
		name: "El cotorro",
		src: "figures/mexican/24.webp",
		imageURL: "",
	},
	{
		id: 25,
		name: "El borracho",
		src: "figures/mexican/25.webp",
		imageURL: "",
	},
	{
		id: 26,
		name: "El negrito",
		src: "figures/mexican/26.webp",
		imageURL: "",
	},
	{
		id: 27,
		name: "El corazon",
		src: "figures/mexican/27.webp",
		imageURL: "",
	},
	{
		id: 28,
		name: "La sandia",
		src: "figures/mexican/28.webp",
		imageURL: "",
	},
	{
		id: 29,
		name: "El tambor",
		src: "figures/mexican/29.webp",
		imageURL: "",
	},
	{
		id: 30,
		name: "El camarón",
		src: "figures/mexican/30.webp",
		imageURL: "",
	},
	{
		id: 31,
		name: "Las jaras",
		src: "figures/mexican/31.webp",
		imageURL: "",
	},
	{
		id: 32,
		name: "El músico",
		src: "figures/mexican/32.webp",
		imageURL: "",
	},
	{
		id: 33,
		name: "La araña",
		src: "figures/mexican/33.webp",
		imageURL: "",
	},
	{
		id: 34,
		name: "El soldado",
		src: "figures/mexican/34.webp",
		imageURL: "",
	},
	{
		id: 35,
		name: "La estrella",
		src: "figures/mexican/35.webp",
		imageURL: "",
	},
	{
		id: 36,
		name: "El cazo",
		src: "figures/mexican/36.webp",
		imageURL: "",
	},
	{
		id: 37,
		name: "El mundo",
		src: "figures/mexican/37.webp",
		imageURL: "",
	},
	{
		id: 38,
		name: "El apache",
		src: "figures/mexican/38.webp",
		imageURL: "",
	},
	{
		id: 39,
		name: "El nopal",
		src: "figures/mexican/39.webp",
		imageURL: "",
	},
	{
		id: 40,
		name: "El alacrán",
		src: "figures/mexican/40.webp",
		imageURL: "",
	},
	{
		id: 41,
		name: "La rosa",
		src: "figures/mexican/41.webp",
		imageURL: "",
	},
	{
		id: 42,
		name: "La calavera",
		src: "figures/mexican/42.webp",
		imageURL: "",
	},
	{
		id: 43,
		name: "La campana",
		src: "figures/mexican/43.webp",
		imageURL: "",
	},
	{
		id: 44,
		name: "El cantarito",
		src: "figures/mexican/44.webp",
		imageURL: "",
	},
	{
		id: 45,
		name: "El venado",
		src: "figures/mexican/45.webp",
		imageURL: "",
	},
	{
		id: 46,
		name: "El sol",
		src: "figures/mexican/46.webp",
		imageURL: "",
	},
	{
		id: 47,
		name: "La corona",
		src: "figures/mexican/47.webp",
		imageURL: "",
	},
	{
		id: 48,
		name: "La chalupa",
		src: "figures/mexican/48.webp",
		imageURL: "",
	},
	{
		id: 49,
		name: "El pino",
		src: "figures/mexican/49.webp",
		imageURL: "",
	},
	{
		id: 50,
		name: "El pescado",
		src: "figures/mexican/50.webp",
		imageURL: "",
	},
	{
		id: 51,
		name: "La palma",
		src: "figures/mexican/51.webp",
		imageURL: "",
	},
	{
		id: 52,
		name: "La maceta",
		src: "figures/mexican/52.webp",
		imageURL: "",
	},
	{
		id: 53,
		name: "El arpa",
		src: "figures/mexican/53.webp",
		imageURL: "",
	},
	{
		id: 54,
		name: "La rana",
		src: "figures/mexican/54.webp",
		imageURL: "",
	},
];
